### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by kuschelnder** [AxstSoftware/ForgeTemplate#1]
A problem occurred configuring root project 'ForgeTemplate'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.asbyth:ForgeGradle:6f53277.
     Searched in the following locations:
       - https://maven.minecraftforge.net/com/github/asbyth/ForgeGradle/6f53277/ForgeGradle-6f53277.pom
       - https://jitpack.io/com/github/asbyth/ForgeGradle/6f53277/ForgeGradle-6f53277.pom
       - https://repo.maven.apache.org/maven2/com/github/asbyth/ForgeGradle/6f53277/ForgeGradle-6f53277.pom
       - https://plugins.gradle.org/m2/com/github/asbyth/ForgeGradle/6f53277/ForgeGradle-6f53277.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by kuschelnder** [comment]
i guess asbyth deleted his repo

**Comment by sdxqw** [comment]
yup he does.
